name: Update Playlist

on:
  workflow_dispatch:  # allow manual trigger
  schedule:
    - cron: "0 */6 * * *"  # runs every 6 hours

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Debug repo structure
        run: ls -R

      - name: Run script
        run: python playlist_updater.py
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
